### ISSUE TITLE
backfill gallery attachment images

### ISSUE THREAD

**Issue by drrobotnik** [toastedlime/wp-attachment-importer#12]
This may be out of scope of the intended usage, but gallery images aren't included in the backfill function. If the ID of an image attachment changes, it'd be extra awesome if your backfill could update this also.

[gallery columns="1" ids="1919,1920,1921,1922,1923"]
https://github.com/toastedlime/wp-attachment-importer/blob/master/index.php#L212

**Comment by piontkowski** [comment]
If you import attachments as the first thing after installing WordPress and importing the other content, then there's nothing to remap, because the attachments are imported with the same post ID. However, if you write posts or upload attachments and then try to import content, then there's a chance imported content will be given a different post ID, and the gallery ID's would be off.

When you used the plugin, did you encounter a broken gallery? Did content already exist before you imported?

**Comment by piontkowski** [comment]
Closing for now.
